import { useEffect, useMemo, useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import BottomNavigation from "../components/layout/BottomNavigation";
import { useCart } from "../context/CartContext";
import { API_URL } from "../lib/api";

type Category = { id:number; title:string; image:string };
type Product = { id:number; title:string; image:string; price:number; discount:number; stock:number; categoryId:number; category:Category };
type Sort = "popular"|"discount"|"newest"|"cheap"|"expensive";
const sortLabels:Record<Sort,string>={popular:"پرفروش‌ترین",discount:"بیشترین تخفیف",newest:"جدیدترین",cheap:"ارزان‌ترین",expensive:"گران‌ترین"};
const formatPrice=(n:number)=>n.toLocaleString("fa-IR");
const finalPrice=(p:Product)=>Math.floor((p.price*(1-p.discount/100))/500)*500;

function SearchProductDetails({product,onClose}:{product:Product;onClose:()=>void}){
 const {quantityOf,addItem,increment,decrement}=useCart();const quantity=quantityOf(product.id);
 return <div className="product-modal" role="dialog" aria-modal="true" aria-label="جزئیات محصول" onClick={onClose}><section className="product-sheet" dir="rtl" onClick={e=>e.stopPropagation()}><button type="button" className="product-close" aria-label="بستن" onClick={onClose}/><div className="product-gallery"><img src={product.image} alt={product.title}/><div className="product-dots" aria-hidden="true"><i/><i/><i/><i/></div></div><h1>{product.title}</h1><div className="product-specs"><div><span>دسته‌بندی:</span><strong>{product.category.title}</strong></div><div><span>ضمانت کالا:</span><strong>تضمین اصالت</strong></div><div><span>شرایط نگهداری:</span><strong>در جای خشک و خنک</strong></div><div><span>ارسال:</span><strong>ارسال سریع</strong></div></div><div className="product-purchase"><div className="product-support-price"><b>تعداد در سبد خرید</b><span><strong>{quantity.toLocaleString("fa-IR")}</strong> عدد</span></div><div className="product-buy-row">{quantity>0?<div className="product-modal-counter" dir="ltr"><button type="button" onClick={()=>decrement(product.id)}>−</button><b>{quantity.toLocaleString("fa-IR")}</b><button type="button" aria-disabled={quantity>=product.stock} onClick={()=>increment(product.id)}>＋</button></div>:<button type="button" aria-disabled={product.stock<=0} onClick={()=>addItem(product)}>{product.stock>0?"افزودن به سبد خرید":"ناموجود"}</button>}<div><span>قیمت کالا</span><strong>{formatPrice(finalPrice(product))}</strong><small>تومان</small></div></div></div></section></div>;
}

export default function Search(){
 const navigate=useNavigate();const [params,setParams]=useSearchParams();const [query,setQuery]=useState(params.get("q")??"");
 const initialCategory=Number(params.get("category"));
 const [products,setProducts]=useState<Product[]>([]);const [categories,setCategories]=useState<Category[]>([]);const [category,setCategoryState]=useState<number|null>(initialCategory>0?initialCategory:null);
 const [selectedProduct,setSelectedProduct]=useState<Product|null>(null);
 const [sort,setSort]=useState<Sort>("popular");const [sortOpen,setSortOpen]=useState(false);const [discountOnly,setDiscountOnly]=useState(false);const [loading,setLoading]=useState(true);const [error,setError]=useState(false);
 const {totalQuantity,quantityOf,addItem,increment,decrement}=useCart();
 useEffect(()=>{const c=new AbortController();Promise.all([fetch(`${API_URL}/products`,{signal:c.signal}),fetch(`${API_URL}/categories`,{signal:c.signal})]).then(async([p,g])=>{if(!p.ok||!g.ok)throw new Error();setProducts(await p.json());setCategories(await g.json())}).catch(e=>{if(e.name!=="AbortError")setError(true)}).finally(()=>setLoading(false));return()=>c.abort()},[]);
 useEffect(()=>{const id=setTimeout(()=>{const next=new URLSearchParams(params);query.trim()?next.set("q",query.trim()):next.delete("q");setParams(next,{replace:true})},250);return()=>clearTimeout(id)},[query]);
 const setCategory=(id:number|null)=>{setCategoryState(id);const next=new URLSearchParams(params);id?next.set("category",String(id)):next.delete("category");setParams(next,{replace:true})};
 const result=useMemo(()=>{const q=query.trim().toLocaleLowerCase("fa");const list=products.filter(p=>(!q||p.title.toLocaleLowerCase("fa").includes(q)||p.category.title.toLocaleLowerCase("fa").includes(q))&&(!category||p.categoryId===category)&&(!discountOnly||p.discount>0));return [...list].sort((a,b)=>sort==="discount"?b.discount-a.discount:sort==="newest"?b.id-a.id:sort==="cheap"?finalPrice(a)-finalPrice(b):sort==="expensive"?finalPrice(b)-finalPrice(a):a.id-b.id)},[products,query,category,discountOnly,sort]);
 return <><main className="catalog-page" onClick={()=>sortOpen&&setSortOpen(false)}>
  <header className="search-page-header" dir="rtl"><button type="button" className="search-brand" onClick={()=>navigate("/home")}><img src="/images/header/logo.png" alt="مادر مارکت"/><img src="/images/header/direction.png" alt=""/></button><div className="search-header-actions" dir="ltr"><button type="button" className="search-icon-button" aria-label="تمرکز روی جستجو" onClick={()=>document.getElementById("product-search")?.focus()}><img src="/images/searchbar/search.png" alt=""/></button><button type="button" className="search-cart-button" onClick={()=>navigate("/basket")}><span className="search-cart-icon"><img src="/images/header/basket.png" alt=""/></span><span><b>مشاهده سبد</b><small dir="ltr"><span>{totalQuantity.toLocaleString("fa-IR")}</span><span>محصول</span></small></span></button></div></header>
  <section className="catalog-search-area" dir="rtl"><form onSubmit={e=>e.preventDefault()}><img src="/images/searchbar/search.png" alt=""/><input id="product-search" autoFocus type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="نام محصول یا دسته‌بندی را جستجو کنید..."/><button type="button" className={query?"visible":""} onClick={()=>setQuery("")} aria-label="پاک کردن">×</button></form></section>
  <section className="catalog-categories" aria-label="دسته‌بندی‌ها" dir="rtl"><button className={!category?"active":""} onClick={()=>setCategory(null)}><span className="catalog-all">همه</span><b>همه</b></button>{categories.map(c=><button key={c.id} className={category===c.id?"active":""} onClick={()=>setCategory(c.id)}><span><img src={c.image} alt=""/></span><b>{c.title}</b></button>)}</section>
  <section className="catalog-chips" dir="rtl">{categories.slice(0,8).map(c=><button key={c.id} className={category===c.id?"active":""} onClick={()=>setCategory(category===c.id?null:c.id)}>{c.title}</button>)}</section>
  <section className="catalog-controls" dir="rtl"><div className="catalog-sort" onClick={e=>e.stopPropagation()}><button onClick={()=>setSortOpen(v=>!v)}><img className="catalog-sort-icon" src="/images/basket/arrow-swap.png" alt=""/> مرتب‌سازی <img className={sortOpen?"catalog-sort-arrow open":"catalog-sort-arrow"} src="/images/basket/arrow-down.png" alt=""/></button>{sortOpen&&<div className="catalog-sort-menu">{(Object.keys(sortLabels) as Sort[]).map(s=><button key={s} className={sort===s?"active":""} onClick={()=>{setSort(s);setSortOpen(false)}}>{sortLabels[s]}</button>)}</div>}</div><button className={discountOnly?"catalog-filter active":"catalog-filter"} onClick={()=>setDiscountOnly(v=>!v)}>٪ تخفیف‌دارها</button><p>{result.length.toLocaleString("fa-IR")} کالا</p></section>
  <section className="catalog-results" aria-live="polite">{loading?<div className="catalog-state"><i/>در حال جستجوی محصولات...</div>:error?<div className="catalog-state">دریافت محصولات با خطا مواجه شد.</div>:result.length?result.map(p=><article className="catalog-card" key={p.id} dir="rtl" role="button" tabIndex={0} onClick={()=>setSelectedProduct(p)} onKeyDown={e=>{if(e.key==="Enter")setSelectedProduct(p)}}><img className="catalog-product-img" src={p.image} alt={p.title}/><div className="catalog-product-body"><h2>{p.title}</h2><small className="catalog-category-name">{p.category.title}</small><div className="catalog-product-row"><div className="catalog-add">{quantityOf(p.id)?<div className="catalog-counter"><button onClick={e=>{e.stopPropagation();decrement(p.id)}}>−</button><b>{quantityOf(p.id).toLocaleString("fa-IR")}</b><button aria-disabled={quantityOf(p.id)>=p.stock} onClick={e=>{e.stopPropagation();increment(p.id)}}>＋</button></div>:<button aria-disabled={p.stock<=0} onClick={e=>{e.stopPropagation();addItem(p)}}>{p.stock>0?"افزودن به سبد":"ناموجود"}</button>}</div><div className="catalog-price">{p.discount>0&&<div><del>{formatPrice(p.price)}</del><span>٪{p.discount.toLocaleString("fa-IR")}</span></div>}<strong>{formatPrice(finalPrice(p))}<small>تومان</small></strong></div></div></div>{p.discount>0&&<footer><b>قیمت با تخفیف</b><span>{formatPrice(finalPrice(p))} تومان</span></footer>}</article>):<div className="catalog-not-found"><span>⌕</span><h2>محصولی پیدا نشد</h2><p>عبارت دیگری بنویسید یا فیلترها را پاک کنید.</p><button onClick={()=>{setQuery("");setCategory(null);setDiscountOnly(false)}}>پاک کردن فیلترها</button></div>}</section>
 </main><BottomNavigation/>{selectedProduct&&<SearchProductDetails product={selectedProduct} onClose={()=>setSelectedProduct(null)}/>}</>;
}
